version: '3.8'

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  warp:
    image: monius/docker-warp-socks:v5
    container_name: warp-ace
    expose:
      - 9091
    restart: unless-stopped
    # privileged: true // probar a ver si va
    cap_add:
      - NET_ADMIN
      # - SYS_ADMIN // probar a ver si va
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 1
      net.ipv4.conf.all.src_valid_mark: 1
    environment:
      - LOG_LEVEL=debug
    logging: *default-logging
    healthcheck:
      test: [ "CMD", "curl", "-sSf", "http://127.0.0.1:9091" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  acestream:
    image: rotiemex/acewarp:latest
    container_name: acestream6878
    volumes:
      - ./acestream.conf:/opt/acestream/acestream.conf
    cap_add:
      - NET_RAW
      - NET_ADMIN
      - SYS_ADMIN
    ports:
      - "8621:8621"
      - "6878:6878"
      - "6879:6879"
    depends_on:
      - warp
    restart: unless-stopped
    logging: *default-logging
    healthcheck:
      test: [ "CMD", "curl", "-sSf", "http://localhost:8621" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  nginx:
    image: nginx:1.29.1
    container_name: nginx-playlist
    volumes:
      - ./playlist:/usr/share/nginx/html:ro
    read_only: true
    tmpfs:
      - /var/cache/nginx
      - /var/run
      - /var/log/nginx
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - DISABLE_IPV6=true
      - IP_RANGES_FETCH_ENABLED=false
      - X_FRAME_OPTIONS=sameorigin
    logging: *default-logging
    healthcheck:
      test: [ "CMD", "curl", "-sSf", "http://localhost/" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  jellyfin:
    image: jellyfin/jellyfin:10.10.6
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/cache:/cache
      - ./jellyfin/media:/media
    ports:
      - "8096:8096"
    depends_on:
      - nginx
    restart: unless-stopped
    logging: *default-logging

  zeronet:
    image: canewsin/zeronet
    container_name: zeronet
    ports:
      - "43110:43110"
    volumes:
      - ./zeronet_data:/root/data
    restart: unless-stopped
    environment:
      - ENABLE_TOR=true
      # https://ipfs.io/ipns/elcano.top
    logging: *default-logging

networks:
  default:
    driver: bridge
