--client-console
# --client-wx
--bind-all
--live-cache-type memory
--vod-cache-type memory
--cache-dir /opt/acestream/cache

--live-buffer 25
--vod-buffer 10

--max-connections 500
--max-peers 50
--max-upload-slots 50
--download-limit 0
--upload-limit 0

--log-file /opt/acestream/acestream.log
--log-level info
--webui_enabled
--webui_port 6879
--webui-password admin_pass
--webui-log /opt/acestream/webui.log