--client-console
# --client-wx
--bind-all
# --disable-network-monitor
--live-cache-type memory
--vod-cache-type memory
--cache-dir /opt/acestream/cache

--live-buffer 25
--vod-buffer 10
# --stream-time-buffer 40 

--max-connections 500
--max-peers 50
--max-upload-slots 50
# --connect-limit 100
--download-limit 0
--upload-limit 0

# --max-memory-size 2147483648
# --memory-cache-size 1073741824 

--log-file /opt/acestream/acestream.log
--log-level info
--webui_enabled
--webui_port 6879
--webui-password admin_pass
--webui-log /opt/acestream/webui.log

# --nat-access-type 1
# --peer-connect-timeout 30 